version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: docker
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: udemy
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - lrz-network    
  api-gateway:
    image: lrz00/api-gateway  
    restart: always
    build: .
    working_dir: /api-gateway
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/udemy?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: lara
      SPRING.DATASOURCE.PASSWORD: root123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db    
    networks:
      - lrz-network    
networks:
  lrz-network:    
    driver: bridge
