name: Continuous Integration with GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List repository files
        run: ls -la

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Compose
        run: docker compose build

      - name: Docker Hub Push
        run: |
          docker tag lrz00/api-gateway:latest ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker tag lrz00/api-gateway:latest ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.run_id }}
